# Generated by Django 2.0.5 on 2018-05-31 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0002_thwurl_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thwurl',
            old_name='date',
            new_name='created_on',
        ),
    ]
