# Generated by Django 2.0.5 on 2018-05-31 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0003_auto_20180531_2315'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thwurl',
            old_name='created_on',
            new_name='created',
        ),
    ]
