# Generated by Django 2.0.5 on 2018-05-31 17:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0004_auto_20180531_2316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thwurl',
            name='created',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
    ]
