# Generated by Django 2.0.5 on 2018-05-31 18:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0005_auto_20180531_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thwurl',
            name='created',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
