# Generated by Django 2.0.5 on 2018-05-31 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0006_auto_20180531_2349'),
    ]

    operations = [
        migrations.AddField(
            model_name='thwurl',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
