# Generated by Django 2.0.5 on 2018-05-31 19:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0007_thwurl_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thwurl',
            name='created',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
