# Generated by Django 2.0.5 on 2018-06-01 01:21

from django.db import migrations, models
import shortener.validators


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0008_auto_20180601_0044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thwurl',
            name='url',
            field=models.CharField(max_length=220, validators=[shortener.validators.validate_url, shortener.validators.validate_dot_com]),
        ),
    ]
