# Generated by Django 2.0.5 on 2018-06-02 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0009_auto_20180601_0651'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thwurl',
            old_name='created',
            new_name='t_created',
        ),
        migrations.AddField(
            model_name='thwurl',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
