# Generated by Django 2.0.5 on 2018-06-02 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0010_auto_20180602_2321'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thwurl',
            name='count',
        ),
    ]
